name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create config.js from secrets
        run: |
          echo "window.ENV = {" > ./public/config.js
          echo "  BASE_URL: '${{ secrets.BASE_URL }}'," >> ./public/config.js
          echo "  API_KEY: '${{ secrets.API_KEY }}'" >> ./public/config.js
          echo "};" >> ./public/config.js

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
